### ISSUE TITLE
import errrors on different versions of pytorch and visualize qustions

### ISSUE THREAD

**Issue by MusherM** [ZhangGongjie/SAM-DETR#2]
First of all, thx for your opensource code!
## Known issues
There are some errors with your import in attention.py
1. 
  ```python
if float(torch.__version__[:3]) < 1.7:
     from torch._overrides import has_torch_function, handle_torch_function
else:
    from torch.overrides import has_torch_function, handle_torch_function
```
It seems quite simple, but when torch.__version__ returns like 1.11.0, this could lead to version error, as float(torch.__version__[:3]) < 1.7 will return 1.1<1.7 True.
I recommand you could split torch.__version__ return by '.' to compare version more precisely.
2. and if pytorch version >=1.8.1 
```python
from torch.nn.modules.linear import  _LinearWithBias
```
will lead to import error, as _LinearWithBias seems not accessable in pytorch>=1.8.1, where can be replaced by
```python
from torch.nn.modules.linear import NonDynamicallyQuantizableLinear as _LinearWithBias
```
I'll appreciate it if you could add version compatability like above with this too
## My question
I'm new to cv so, forgive me if my question is easy.
After training on my own dataset, I get many .pth files in my output directory, I think it contains model parameters. 
I want to know that having trained model parameters, how could I load this model to detect on 1 specific image. 
That's to say, I want to give the model an image, and get back model's detection result in some format.
Thx if you could reply.

**Comment by ZhangGongjie** [comment]
@MusherM   Hi, thank you so much for reporting bugs and their solutions!  👍👍 

I will check these issues tomorrow. Thank you!

Regarding your question, I will prepare a "demo.py" to perform inference on one image and show the results. I will try to release the codes by this weekend.  I will let you know when it's done.

**Comment by MusherM** [comment]
Thx, I'm doing my undergraduate graduation design, meeting problems every day, offering issues but getting few replies.
Much thx for your help and positive mataining, wish you have a good day
And wish I can get acievements in cv like u😊

**Comment by ZhangGongjie** [comment]
Thank you for your compliments! You made my day :)  Have a wonderful day!

The issues have been fixed based on your recommendations. Thanks once again!

**Comment by MusherM** [comment]
You are welcome. Let me know if u release your demo.py😜
Another interesting thing is that my graduate design is about few-shot detection on satellite images, and this project seems not be few-shot, so I continue looking for few-shot object detection projects, guess I find what?
![截屏2022-04-15 14 06 40](https://user-images.githubusercontent.com/50447418/163528643-fc5a814a-8258-44bb-bdfb-4f5d2c485b54.png)
I'll move on to your meta-detr project and keep bothering u ,lol

**Comment by ZhangGongjie** [comment]
@MusherM  Thank you! You are most welcome to keep contributing! Ideas, questions, and bugs are all welcome!

FYI, I have updated demo.py for your reference. I will prepare some instructions on README.md tomorrow.

**Comment by ZhangGongjie** [comment]
I tried to keep demo.py simple for you to understand. 

`demo.py` performs inference on all images in the folder of `images`. Since the model gives a fixed number of predictions per image (300 in SAM-DETR), we only keep those predictions with confidence scores higher than `0.5`.

Lines 220-222 are the model's detection results in certain formats. I also visualize the boxes and stored them in `./images`.

**Comment by MusherM** [comment]
thx a lot
BTW I’m Chinese too, after we spoke English all this long
Any way, others can understand though lol


> 在 2022年4月17日，23:18，Gongjie Zhang ***@***.***> 写道：
> 
> FYI

**Comment by MusherM** [comment]
Thx for your help!
You really helped me a lot, much love for uuuuuuuuuuuuuuu

**Comment by ZhangGongjie** [comment]
Thank you! Good to learn that I helped. Good luck with your graduation project!
