### ISSUE TITLE
Data preparation mistake

### ISSUE THREAD

**Issue by MusherM** [ZhangGongjie/SAM-DETR#3]
Hey!It's me again, I forgot to tell u another small mistake in Data Preparation
```bash
code_root/
└── data/
    └── coco/
        ├── train2017/
        ├── val2017/
        └── annotations/
        	├── instances_train2017.json
        	└── instances_val2017.json
```
This does not seem to meet the file structure written in your code.
The correct Tree seems to be like this:
```bash
code_root/
└── data/
    └── coco/
        └── images/
               ├── train2017/
               └──val2017/
        └── annotations/
        	├── instances_train2017.json
        	└── instances_val2017.json
```
Please check it out, thx

**Comment by ZhangGongjie** [comment]
Thank you so much for providing issues. @MusherM   💯 👍 

I have changed the code for parsing the dataset so that the dataset directory does not need to change. Have a nice day!
