### ISSUE TITLE
Why the q_content is the same as the q_content_points?

### ISSUE THREAD

**Issue by rockywind** [ZhangGongjie/SAM-DETR#9]
Hi,
What's the difference between the q_content and q_content_points?
![image](https://user-images.githubusercontent.com/14838781/186350294-5b87babc-1daf-4316-b4a0-3af95d11909a.png)

**Comment by ZhangGongjie** [comment]
Hi, thanks for your comments.

I checked the codes. It turned out that they are redundant. Just one RoIAign operation is enough.

**Comment by rockywind** [comment]
thanks for your reply!
